### ISSUE TITLE
Improve the `about` Page

### ISSUE THREAD

**Issue by Abhilekhgautam** [noskofficial/noskofficial.github.io#20]
### The Problem:

The about page looks creepy:
![image](https://user-images.githubusercontent.com/67783712/235859651-e8391600-beb8-4c62-ae63-91ee180652b1.png)

The about page can be greatly improved.
### Suggested improvements:
1. Improving page layout.
2. Better Content for the page.
3. Responsive and better images.

**Comment by Bibekdhkl** [comment]
Ok, I will work on this!
