### ISSUE TITLE
Input validation and mailing support in contact

### ISSUE THREAD

**Issue by bishalx0** [noskofficial/noskofficial.github.io#24]
- validation for email input
- map this form to the Gmail instance
- at least make it working

Currently, it is not 😔

![image](https://user-images.githubusercontent.com/67583667/235982902-d8103f62-d8cb-4a83-9bcf-bf6a4d49c590.png)

**Comment by SatyaRajAwasth1** [comment]
I worked for it on issue #23 . There is pull request for that at #35

**Comment by bishalx0** [comment]
@SatyaRajAwasth1  Your PR #35 is deployed. Now you can activate it. Due to no activation, we are unable to test input validation.

**Comment by bishalx0** [comment]
After merging #38 

There is no input validation found in the email. It seems there is no mailing support just receiving input.

![image](https://github.com/noskofficial/noskofficial.github.io/assets/67583667/94932d80-bf70-4a2b-8ac0-d20a0f99107a)
![image](https://github.com/noskofficial/noskofficial.github.io/assets/67583667/1e5b1b40-a773-4c0c-a0af-ab2c17c96c5d)

**Comment by SatyaRajAwasth1** [comment]
Its working well from my device.
![image](https://github.com/noskofficial/noskofficial.github.io/assets/77236280/9151d097-5c00-4e0d-8302-934091e35ad6)

this is the success page, I just have checked whether that is email or not. I haven't kept any regext to validate fields.

![image](https://github.com/noskofficial/noskofficial.github.io/assets/77236280/770b5817-81aa-429e-bc08-fc28c0ca7677)

**Comment by bishalx0** [comment]
@SatyaRajAwasth1 Does it send mail to NOSK's email address from provided mail address? or what it does?

**Comment by SatyaRajAwasth1** [comment]
@bishalx0 Yes, after submitting form all the details filled in form are sent to the email of NOSK.

**Comment by SatyaRajAwasth1** [comment]
@bishalx0 Actually the logic is just to sent those form data to our email, it doesn't send from the email provided on the form field. But using third party API system the data of form is sent to NOSK email.

**Comment by bishalx0** [comment]
> @bishalx0 Actually the logic is just to sent those form data to our email, it doesn't send from the email provided on the form field. But using third party API system the data of form is sent to NOSK email.

Okey well!
