### ISSUE TITLE
Figma Design for NOSK Website

### ISSUE THREAD

**Issue by Bibekdhkl** [noskofficial/noskofficial.github.io#36]
I have created About Us Page design for now which you can access from [here](https://www.figma.com/file/uxc4Whe5R6qpVgjJCodkiy/NOSK-website-Design?type=design&node-id=0%3A1&t=sDvGc28OazisBbai-1)

do let me know if you want to contribute on the design with suggestions and feedbacks!

**Comment by bishalx0** [comment]
@Bibekdhkl what is happening to this issue?
