### ISSUE TITLE
Fix: issue on event status

### ISSUE THREAD

**Issue by SatyaRajAwasth1** [noskofficial/noskofficial.github.io#53]
For now it is fine if there is any event added on the events.json. It gets automatically fetched to teh event registeration page.

But, when showing status "registeration open" or "completed" for the event the logic first checks year if it is greater or equal then it checks month+1 greater or equal if it becomes true it means that the event month is the next month the day is checked if the month is true. Think the event month is next that is tru but the day is smaller than today. which makes logic false and event status becomes "completed".

![image](https://github.com/noskofficial/noskofficial.github.io/assets/77236280/e119e836-6c0e-4a91-9a89-48b359380fa2)

**Comment by officialnosk** [comment]
fixed and merged by #57
