### ISSUE TITLE
wrong Discord link

### ISSUE THREAD

**Issue by dinesh-58** [noskofficial/noskofficial.github.io#60]
The discord link points to one of the server channels, which is only accessible to users that are already part of the discord server. Instead, put an invite link which you can get from the drop down at the top left corner (next to the server name). Make sure to set it to never expire

**Comment by tmsagarofficial** [comment]
Hey @Abhilekhgautam I think this will be a concern,
I tried to research about what the issue was and I found this when I tried to hop on to the NosK discord server

![image](https://github.com/user-attachments/assets/27a5010b-7242-45dd-82be-d93b674395cf)

**Comment by tmsagarofficial** [comment]
Would love to work on a fix for this issue as I've experience handling all things discord.
