### ISSUE TITLE
Add Pagination to Event Page

### ISSUE THREAD

**Issue by Abhilekhgautam** [noskofficial/noskofficial.github.io#66]
The event page displays all the events in a single page: [NOSK Event Page](https://nosk.org.np/site/html/events.html)

It'd be better if we could add pagination to the page with just 10 events in a page.

**Comment by withoutwax13** [comment]
Good day @Abhilekhgautam

I did work on this issue on this PR: [https://github.com/noskofficial/noskofficial.github.io/pull/70](url)
