### ISSUE TITLE
Fix: About Page

### ISSUE THREAD

**Issue by Abhilekhgautam** [noskofficial/noskofficial.github.io#76]
The texts in [about page](https://nosk.org.np/site/html/about.html) are quite unreadable (may be due to the background image).

Can we fix this by improving font, font-style or something else.
![image](https://github.com/user-attachments/assets/3d979d83-4987-4a91-9b0a-65eb91f1fc7d)

**Comment by tmsagarofficial** [comment]
Hey this looks like something that i can work on , can you assign this issue to me?

**Comment by Abhilekhgautam** [comment]
Ok @tmsagarofficial  assigned this to you.

**Comment by tmsagarofficial** [comment]
check this PR, it should be working good 😅  @Abhilekhgautam

**Comment by suddhababa** [comment]
I can do some changes on it , can you assign me this issue to me?

**Comment by tmsagarofficial** [comment]
Since I'm on it I'll finish this @suddhababa ,
Feel free to work on other live issues.😃

**Comment by Abhilekhgautam** [comment]
@suddhababa I am happy with the current progress. Check out other issues, if you want to contribute.

**Comment by tmsagarofficial** [comment]
Thanks for letting me contribute 🚀
